language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xadamus/docker-sandbox -f Dockerfile.dev .

script:
  - docker run -e CI=true xadamus/docker-sandbox npm run test
